---
name: Docs
"on":
  push:
    # Only targets main branch to avoid amplification effects of auto-fixing
    # the exact same stuff in multiple non-rebased branches.
    branches:
      - main

jobs:

  docs:
    uses: slickag/mpm-workflows/.github/workflows/docs.yaml@main